{% set name = "laplace-torch" %}
{% set version = "0.1a2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/laplace-torch-{{ version }}.tar.gz
  sha256: 9e9329ad7463eddd3a8c9c0b3647800a8f200886d941ba90a3b664739e4a8500

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 ==2.17                # [linux64]
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - asdfghjkl
    - backpack-for-pytorch
    - python >=3.8
    - pytorch
    - torchvision
    - numpy

test:
  imports:
    - laplace
    - laplace.curvature

about:
  home: https://github.com/AlexImmer/Laplace
  summary: laplace - Laplace approximations for deep learning
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
