context:
  name: laplace-torch
  version: 0.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 641823a6d3e1dcb8297202b896ae2969334bf96df9a4a6f8cf688896d67d96f2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ stdlib("c") }}
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - asdfghjkl
    - backpack-for-pytorch
    - curvlinops-for-pytorch
    - python >=3.8
    - pytorch
    - torchvision
    - torchmetrics
    - numpy
    - tqdm
    - opt_einsum
    - asdfghjkl

tests:
  - python:
      imports:
        - laplace
        - laplace.curvature

about:
  summary: laplace - Laplace approximations for deep learning
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/AlexImmer/Laplace

extra:
  recipe-maintainers:
    - Tobias-Fischer
